# file path configuration
SCRATCH_ROOT=${SCRATCH_ROOT:-}

# barcode configuration
# set BARCODE_WHITELIST to a custom whitelist file path if needed
# empty BARCODE_WHITELIST will use the default whitelist in docs/barcodes/barcodes50.tsv
BARCODE_WHITELIST=${BARCODE_WHITELIST:-}
# batches are assigned to these chunks in round-robin order
BARCODE_CHUNK=${BARCODE_CHUNK:-4}
# paired reads in each dispatched batch
BARCODE_BATCH_SIZE=${BARCODE_BATCH_SIZE:-50000}
BARCODE_COMPRESSION_STEP=${BARCODE_COMPRESSION_STEP:-shell}
BARCODE_GZIP_LEVEL=${BARCODE_GZIP_LEVEL:-6}
BARCODE_LINKER_BC=${BARCODE_LINKER_BC:-ATCCACGTGCTTGAGAGGCCAGAGCATTCG}
BARCODE_INSERT_LEFT=${BARCODE_INSERT_LEFT:-CATCGGCGTACGACTAGATGTGTATAAGAGACAG}
# methylated C positions in BARCODE_INSERT_LEFT, using 0-based coordinates
BARCODE_METHYLATED_C_POSITIONS=${BARCODE_METHYLATED_C_POSITIONS:-3,6,10}
BARCODE_LINKER_EDIT_DISTANCE=${BARCODE_LINKER_EDIT_DISTANCE:-1}
BARCODE_HAMMING_DISTANCE=${BARCODE_HAMMING_DISTANCE:-1}
BARCODE_INSERT_LEFT_EDIT_DISTANCE=${BARCODE_INSERT_LEFT_EDIT_DISTANCE:-1}
BARCODE_PROGRESS_READS=${BARCODE_PROGRESS_READS:-1000000}

# resource configuration
SBATCH_OUTPUT=${SBATCH_OUTPUT:-%x_%j.out}
SBATCH_ERROR=${SBATCH_ERROR:-%x_%j.err}
SBATCH_REQUEUE=${SBATCH_REQUEUE:-true}

FASTP_NAME=${FASTP_NAME:-fastp}
FASTP_THREADS=${FASTP_THREADS:-8}
FASTP_PARTITION=${FASTP_PARTITION:-}
FASTP_MEM=${FASTP_MEM:-16G}
FASTP_TIME=${FASTP_TIME:-24:00:00}

BARCODE_NAME=${BARCODE_NAME:-barcode}
BARCODE_THREADS=${BARCODE_THREADS:-$BARCODE_CHUNK}
BARCODE_PARTITION=${BARCODE_PARTITION:-}
BARCODE_MEM=${BARCODE_MEM:-64G}
BARCODE_TIME=${BARCODE_TIME:-24:00:00}
