# execution mode: local (run directly) or hpc (submit via sbatch)
RUN_MODE=${RUN_MODE:-hpc}

# Reference configuration. SCRATCH_ROOT is used only by barcode, pool, call,
# and methscan; all other stages read and write the persistent sample directory.
SCRATCH_ROOT=${SCRATCH_ROOT:-}
# TAPS/TAPS-v2 bwa index prefix or indexed reference FASTA
BWA_INDEX=${BWA_INDEX:-}
# Absolute paths to spike-in BWA indexes used by TAPS/TAPS-v2 align.
# Bash equivalent of: {"lambda": "/path/to/index", "puc19": "/path/to/index"}
declare -A BWA_SPIKE_IN_INDEXES=(
    [lambda]=""
    [puc19]=""
)
# EM-seq/Cabernet/SmC biscuit-indexed reference FASTA
BISCUIT_REFERENCE=${BISCUIT_REFERENCE:-}
# Absolute paths to spike-in biscuit indexes used by EM-seq/Cabernet/SmC align.
# Bash equivalent of: {"lambda": "/path/to/index", "puc19": "/path/to/index"}
declare -A BISCUIT_SPIKE_IN_INDEXES=(
    [lambda]=""
    [puc19]=""
)
# Host reference FASTA used for methylation calling.
CALL_REFERENCE=${CALL_REFERENCE:-}
# Absolute paths to spike-in FASTAs used for methylation calling; each FASTA needs a .fai index.
# Bash equivalent of: {"lambda": "/path/to/FASTA", "puc19": "/path/to/FASTA"}
declare -A CALL_SPIKE_IN_REFERENCES=(
    [lambda]=""
    [puc19]=""
)

# barcode extraction configuration
# set BARCODE_WHITELIST to a custom whitelist file path if needed
# empty BARCODE_WHITELIST will use the default whitelist in docs/barcodes/barcodes50.tsv
BARCODE_WHITELIST=${BARCODE_WHITELIST:-}
# batches are assigned to these chunks in round-robin order
BARCODE_CHUNK=${BARCODE_CHUNK:-4}
# paired reads in each dispatched batch
BARCODE_BATCH_SIZE=${BARCODE_BATCH_SIZE:-50000}
# compression step for barcode extraction: shell (gzip) or python (zlib)
BARCODE_COMPRESSION_STEP=${BARCODE_COMPRESSION_STEP:-python}
BARCODE_GZIP_LEVEL=${BARCODE_GZIP_LEVEL:-1}
BARCODE_LINKER_BC=${BARCODE_LINKER_BC:-ATCCACGTGCTTGAGAGGCCAGAGCATTCG}
BARCODE_INSERT_LEFT=${BARCODE_INSERT_LEFT:-CATCGGCGTACGACTAGATGTGTATAAGAGACAG}
# methylated C positions in BARCODE_INSERT_LEFT, using 0-based coordinates
BARCODE_METHYLATED_C_POSITIONS=${BARCODE_METHYLATED_C_POSITIONS:-3,6,10}
BARCODE_LINKER_EDIT_DISTANCE=${BARCODE_LINKER_EDIT_DISTANCE:-1}
BARCODE_HAMMING_DISTANCE=${BARCODE_HAMMING_DISTANCE:-1}
BARCODE_INSERT_LEFT_EDIT_DISTANCE=${BARCODE_INSERT_LEFT_EDIT_DISTANCE:-1}
BARCODE_PROGRESS_READS=${BARCODE_PROGRESS_READS:-1000000}

# SmC barcode extraction and strand-splitting configuration.
SMC_BARCODE_WHITELIST=${SMC_BARCODE_WHITELIST:-}
SMC_LINKER_BC=${SMC_LINKER_BC:-ATCCACGTGCTTGAGCGCGCTGCATACTTG}
SMC_INSERT_LEFT=${SMC_INSERT_LEFT:-TGCAGTCGTGCCATGAGATGTGTATAAGAGACAG}
SMC_MAX_CONVERSION_MISMATCHES=${SMC_MAX_CONVERSION_MISMATCHES:-4}
SMC_MINIMUM_SCORE_MARGIN=${SMC_MINIMUM_SCORE_MARGIN:-3}
# Ambiguous/discarded FASTQs are not used downstream. Saving them adds I/O and
# compression time; set to 1 only when they are needed for troubleshooting.
SMC_SAVE_UNINFORMATIVE_FASTQ=${SMC_SAVE_UNINFORMATIVE_FASTQ:-0}

# genome alignment configuration
# aligner threads used by each independent alignment task
ALIGN_THREADS_PER_CHUNK=${ALIGN_THREADS_PER_CHUNK:-8}
# aligner threads used by each spike-in FASTQ chunk
SPIKE_ALIGN_THREADS_PER_CHUNK=${SPIKE_ALIGN_THREADS_PER_CHUNK:-8}
# paired-end library mode for EM-seq/Cabernet: 1 for directional, 0 for non-directional
# SmC always uses directional mode 1 after Watson/Crick mate assignment.
BISCUIT_DIRECTIONAL_MODE=${BISCUIT_DIRECTIONAL_MODE:-1}

# BAM pooling configuration
# per-thread memory for samtools sort (defaults to POOL_MEM/POOL_THREADS if empty)
POOL_SORT_MEM=${POOL_SORT_MEM:-48G}

# M-bias configuration
# all: host and configured spike-ins; host: host only; spike: spike-ins only
MBIAS_MODE=${MBIAS_MODE:-all}
# Host is sampled deterministically; for SmC the limit applies independently
# to the Watson and Crick pools. Spike-in pooled BAMs are processed in full.
MBIAS_HOST_SUBSAMPLE_FRACTION=${MBIAS_HOST_SUBSAMPLE_FRACTION:-0.1}
# Maximum selected host alignment records per M-bias target; 0 disables the limit.
MBIAS_HOST_MAX_RECORDS=${MBIAS_HOST_MAX_RECORDS:-10000000}
MBIAS_MAX_CYCLE=${MBIAS_MAX_CYCLE:-150}
# Cycles whose total CpG coverage does not exceed this are skipped in M-bias outputs.
MBIAS_MIN_CYCLE_COVERAGE=${MBIAS_MIN_CYCLE_COVERAGE:-500}
# Original R1 length before barcode removal; 0 uses trimmed-R1-relative cycles.
MBIAS_R1_ORIGINAL_LENGTH=${MBIAS_R1_ORIGINAL_LENGTH:-150}
MBIAS_MIN_BASE_QUALITY=${MBIAS_MIN_BASE_QUALITY:-30}
MBIAS_MIN_MAPPING_QUALITY=${MBIAS_MIN_MAPPING_QUALITY:-10}
MBIAS_SAMPLING_SEED=${MBIAS_SAMPLING_SEED:-42}
# Maximum absolute deviation from the central M-bias baseline allowed for a stable cycle.
MBIAS_CUTOFF_RATE_TOLERANCE=${MBIAS_CUTOFF_RATE_TOLERANCE:-0.05}

# methylation calling configuration
CALL_CHROMOSOMES=${CALL_CHROMOSOMES:-chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chrX}
CALL_MITO_CHROMOSOMES=${CALL_MITO_CHROMOSOMES:-chrM}
CALL_CONTEXT_MODE=${CALL_CONTEXT_MODE:-both} # Options: cg, ch, both
SPIKE_CALL_MODE=${SPIKE_CALL_MODE:-all} # Options: all, mito, spike
CALL_MIN_BASE_QUALITY=${MBIAS_MIN_BASE_QUALITY}
CALL_MIN_MAPPING_QUALITY=${MBIAS_MIN_MAPPING_QUALITY}
CALL_MAX_DEPTH=${CALL_MAX_DEPTH:-1000000}
CALL_BATCH_SIZE=${CALL_BATCH_SIZE:-10000000}
CALL_JOBS=${CALL_JOBS:-16}

# CpG saturation analysis configuration.
SATURATION_READS_THRESHOLD=${SATURATION_READS_THRESHOLD:-10000}
SATURATION_PRED_FRACTION=${SATURATION_PRED_FRACTION:-2.0}
SATURATION_LINEAR_R2_THRESHOLD=${SATURATION_LINEAR_R2_THRESHOLD:-0.99}

# Context-specific VMR matrix generation in the MethSCAn stage.
METHSCAN_CHUNKSIZE=${METHSCAN_CHUNKSIZE:-10000000}
METHSCAN_CG_MIN_SITES=${METHSCAN_CG_MIN_SITES:-10000}
METHSCAN_CA_MIN_SITES=${METHSCAN_CA_MIN_SITES:-90000}
METHSCAN_CC_MIN_SITES=${METHSCAN_CC_MIN_SITES:-90000}
METHSCAN_CT_MIN_SITES=${METHSCAN_CT_MIN_SITES:-90000}

# SLURM resource configuration
SBATCH_OUTPUT=${SBATCH_OUTPUT:-%x_%j.out}
SBATCH_ERROR=${SBATCH_ERROR:-%x_%j.err}
SBATCH_REQUEUE=${SBATCH_REQUEUE:-true}

FASTP_NAME=${FASTP_NAME:-fastp}
FASTP_THREADS=${FASTP_THREADS:-8}
FASTP_PARTITION=${FASTP_PARTITION:-}
FASTP_MEM=${FASTP_MEM:-16G}
FASTP_TIME=${FASTP_TIME:-24:00:00}

BARCODE_NAME=${BARCODE_NAME:-barcode}
BARCODE_THREADS=${BARCODE_THREADS:-$BARCODE_CHUNK}
BARCODE_PARTITION=${BARCODE_PARTITION:-}
BARCODE_MEM=${BARCODE_MEM:-64G}
BARCODE_TIME=${BARCODE_TIME:-48:00:00}

ALIGN_NAME=${ALIGN_NAME:-align}
ALIGN_THREADS=${ALIGN_THREADS:-$((BARCODE_CHUNK * ALIGN_THREADS_PER_CHUNK))}
ALIGN_PARTITION=${ALIGN_PARTITION:-}
ALIGN_MEM=${ALIGN_MEM:-128G}
ALIGN_TIME=${ALIGN_TIME:-96:00:00}

SPIKE_ALIGN_NAME=${SPIKE_ALIGN_NAME:-spike-align}
SPIKE_ALIGN_THREADS=${SPIKE_ALIGN_THREADS:-$((BARCODE_CHUNK * SPIKE_ALIGN_THREADS_PER_CHUNK))}
SPIKE_ALIGN_PARTITION=${SPIKE_ALIGN_PARTITION:-}
SPIKE_ALIGN_MEM=${SPIKE_ALIGN_MEM:-64G}
SPIKE_ALIGN_TIME=${SPIKE_ALIGN_TIME:-48:00:00}

POOL_NAME=${POOL_NAME:-pool}
POOL_THREADS=${POOL_THREADS:-4}
POOL_PARTITION=${POOL_PARTITION:-}
POOL_MEM=${POOL_MEM:-256G}
POOL_TIME=${POOL_TIME:-48:00:00}

MBIAS_NAME=${MBIAS_NAME:-mbias}
MBIAS_THREADS=${MBIAS_THREADS:-1}
MBIAS_PARTITION=${MBIAS_PARTITION:-}
MBIAS_MEM=${MBIAS_MEM:-16G}
MBIAS_TIME=${MBIAS_TIME:-24:00:00}

CALL_NAME=${CALL_NAME:-call}
CALL_THREADS=${CALL_THREADS:-$CALL_JOBS}
CALL_PARTITION=${CALL_PARTITION:-}
CALL_MEM=${CALL_MEM:-64G}
CALL_TIME=${CALL_TIME:-24:00:00}

SPIKE_CALL_NAME=${SPIKE_CALL_NAME:-spike-call}
SPIKE_CALL_THREADS=${SPIKE_CALL_THREADS:-1}
SPIKE_CALL_PARTITION=${SPIKE_CALL_PARTITION:-}
SPIKE_CALL_MEM=${SPIKE_CALL_MEM:-32G}
SPIKE_CALL_TIME=${SPIKE_CALL_TIME:-24:00:00}

SATURATION_NAME=${SATURATION_NAME:-saturation}
SATURATION_THREADS=${SATURATION_THREADS:-1}
SATURATION_PARTITION=${SATURATION_PARTITION:-}
SATURATION_MEM=${SATURATION_MEM:-16G}
SATURATION_TIME=${SATURATION_TIME:-24:00:00}

SUMMARY_NAME=${SUMMARY_NAME:-summary}
SUMMARY_THREADS=${SUMMARY_THREADS:-1}
SUMMARY_PARTITION=${SUMMARY_PARTITION:-}
SUMMARY_MEM=${SUMMARY_MEM:-16G}
SUMMARY_TIME=${SUMMARY_TIME:-24:00:00}

METHSCAN_NAME=${METHSCAN_NAME:-methscan}
METHSCAN_THREADS=${METHSCAN_THREADS:-10}
METHSCAN_PARTITION=${METHSCAN_PARTITION:-}
METHSCAN_MEM=${METHSCAN_MEM:-64G}
METHSCAN_TIME=${METHSCAN_TIME:-24:00:00}
